name: x86-windows

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev", "sdr-1.0.4" ]

env:
  BUILD_TYPE: Release

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt", "toolchains/ubuntu/*"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup vcpkg with caching
      uses: friendlyanon/setup-vcpkg@v1
      with: 
        committish: c9f906558f9bb12ee9811d6edc98ec9255c6cda5
        path: vcpkg

    - name: Install python mako
      run: python -m pip install mako

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build-windows -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE:STRING=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -A"x64" -G"Visual Studio 17 2022"

    - name: Build
      run: ./toolchains/windows/build.bat

    - name: Create package
      shell: sh
      run: ./toolchains/windows/create_package.sh

    - name: Upload files (Release)
      uses: actions/upload-artifact@v3
      with:
        name: sdrpp_dab_radio_plugin_windows
        path: ${{github.workspace}}/plugin_package
